Added easy versioning to build script

diff --git a/services/rules/scripts/build-container b/services/rules/scripts/build-container
--- a/services/rules/scripts/build-container
+++ b/services/rules/scripts/build-container
@@ -6,11 +6,15 @@ VERSION=${VERSION:-""}
 REGISTRY=${REGISTRY:-"gcf-artifacts"}
 REGION=${REGION:-""}
 PROJECT=${PROJECT:-""}
+INC_MAJOR=${INC_MAJOR:-false}
+INC_MINOR=${INC_MINOR:-false}
+INC_PATCH=${INC_PATCH:-false}
 
 while [ $# -gt 0 ]; do
    if [[ $1 == *"--"* ]]; then
         PARAM="${1/--/}"
         PARAM="$(echo $PARAM | tr 'a-z' 'A-Z')"
+        PARAM="$(echo $PARAM | tr '-' '_')"
         if [[ -z $2 ]] || [[ $2 == *"--"* ]] || [[ $2 == "" ]]; then
           declare $PARAM=true
         else
@@ -24,8 +28,32 @@ done
 
 if [[ -z $VERSION ]]; then
   PACKAGE_JSON_VERSION="$(jq -r '.version' package.json)"
-  echo "[ $(date +%T) ] Missing flag [version]. Using version from package.json ($PACKAGE_JSON_VERSION)."
-  VERSION=$PACKAGE_JSON_VERSION
+
+  MAJOR=$(echo $PACKAGE_JSON_VERSION | cut -d. -f1)
+  MINOR=$(echo $PACKAGE_JSON_VERSION | cut -d. -f2)
+  PATCH=$(echo $PACKAGE_JSON_VERSION | cut -d. -f3)
+
+  if [ $INC_MAJOR == true ]; then
+    MAJOR=$(expr $MAJOR + 1)
+  fi
+
+  if [ $INC_MINOR == true ]; then
+    MINOR=$(expr $MINOR + 1)
+  fi
+
+  if [ $INC_PATCH == true ]; then
+    PATCH=$(expr $PATCH + 1)
+  fi
+
+  if [[ ( $INC_MAJOR == true ) || ( $INC_MINOR == true ) || ( $INC_PATCH == true ) ]]; then
+    VERSION="$MAJOR.$MINOR.$PATCH"
+    echo "[ $(date +%T) ] Incrementing package.json version. Was $PACKAGE_JSON_VERSION will be $VERSION."
+  fi
+
+  if [[ ( $INC_MAJOR == false ) && ( $INC_MINOR == false ) && ( $INC_PATCH == false ) ]]; then
+    echo "[ $(date +%T) ] Missing flag [version]. Using version from package.json ($PACKAGE_JSON_VERSION)."
+    VERSION=$PACKAGE_JSON_VERSION
+  fi
 fi
 
 if [[ -z $PROJECT ]]; then
